# Generated by Django 5.0.1 on 2024-03-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash On Delivery"), ("OP", "Online Payment")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
