# Generated by Django 5.0.1 on 2024-03-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_full_name_order_first_name_order_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payable",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
