# Generated by Django 5.0.1 on 2024-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_order_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "cash on delivery"),
                    ("online_payment", "online payment"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
    ]
