# Generated by Django 5.0.1 on 2024-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash On Delivery"), ("OP", "Online Payment")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
