# Generated by Django 5.0.1 on 2024-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_slider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
